import Foundation

struct FacemaxxingProtocol: Identifiable, Hashable {
    let id: String
    let title: String
    let category: String
    let difficulty: String
    let summary: String
    let steps: [String]
    let notes: String
    let psl: [String]
}

enum FacemaxxingData {
    static let categories: [String] = protocols.reduce(into: []) { if !$0.contains($1.category) { $0.append($1.category) } }
    static let pslDimensions = ["Harmony", "Dimorphism", "Angularity", "Misc"]

    static let protocols: [FacemaxxingProtocol] = [
        .init(id: "mewing", title: "Mewing", category: "Posture", difficulty: "Daily habit",
              summary: "Tongue posture against the palate to support midface and jawline development.",
              steps: [
                "Rest the entire tongue (not just the tip) flat against the roof of your mouth",
                "Keep teeth lightly touching, lips sealed",
                "Breathe through the nose at all times",
                "Hold posture during all idle moments",
              ],
              notes: "Originally from orthodontist John Mew. Adult bone remodelling is slow. Consistency over months.",
              psl: ["Harmony", "Angularity"]),
        .init(id: "chewing", title: "Hard Chewing", category: "Muscle", difficulty: "15 min/day",
              summary: "Mastic gum or jawliner to load the masseter and temporalis.",
              steps: [
                "Use mastic gum (Falim, Mastiha) or a silicone jawliner",
                "Chew evenly on both sides to avoid asymmetry",
                "10 to 20 minutes per session, 1 to 2 sessions per day",
                "Stop if you feel TMJ pain or clicking",
              ],
              notes: "Hypertrophies the masseter, sharpening the lower face outline.",
              psl: ["Angularity", "Dimorphism"]),
        .init(id: "posture", title: "Posture Reset", category: "Posture", difficulty: "5 min/day",
              summary: "Chin tucks, face pulls, thoracic extension to fix forward head posture.",
              steps: [
                "Chin tucks: 3 sets of 10, hold each rep 5 seconds",
                "Band face pulls: 3 sets of 15",
                "Doorway pec stretch: 30 seconds per side",
                "Wall angels: 3 sets of 10",
              ],
              notes: "Forward head posture flattens the jawline and shortens the neck. Single biggest side-profile lever.",
              psl: ["Harmony", "Angularity"]),
        .init(id: "sleep", title: "Sleep Hygiene", category: "Recovery", difficulty: "Nightly",
              summary: "Sleep on your back to avoid asymmetry and morning puffiness.",
              steps: [
                "Sleep supine with a thin pillow",
                "Tape mouth shut to enforce nasal breathing",
                "7 to 9 hours, dark room, cool temperature",
                "No screens 30 minutes before bed",
              ],
              notes: "Side sleeping compresses one side of the face for hours. Stomach sleeping is the worst.",
              psl: ["Harmony", "Misc"]),
        .init(id: "hydration", title: "Hydration and Sodium", category: "Diet", difficulty: "Daily",
              summary: "Reduce facial bloat by managing water and salt intake.",
              steps: [
                "2 to 3 L water per day, more if active",
                "Cut processed foods and restaurant meals",
                "Cut alcohol -- destroys sleep and bloats the face",
                "Track sodium for one week",
              ],
              notes: "Bloat is the single biggest factor in face puffiness.",
              psl: ["Angularity", "Misc"]),
        .init(id: "skin", title: "Minimal Skincare", category: "Skin", difficulty: "5 min/day",
              summary: "Three-step routine: cleanse, moisturize, sunscreen.",
              steps: [
                "Morning: gentle cleanser, moisturizer, SPF 30+",
                "Night: gentle cleanser, moisturizer",
                "Add tretinoin or adapalene 2-3x/week after a month",
                "Avoid harsh scrubs and alcohol toners",
              ],
              notes: "Sunscreen is non-negotiable. UV is the primary driver of skin ageing.",
              psl: ["Misc"]),
        .init(id: "sun", title: "Sun Exposure", category: "Light", difficulty: "Daily",
              summary: "Morning sunlight for circadian rhythm. Protect the face from UV.",
              steps: [
                "10 to 20 minutes of morning sun on the body, not the face",
                "Wear SPF and a hat at midday",
                "Get vitamin D blood test annually",
                "Supplement D3 + K2 if deficient",
              ],
              notes: "Morning light anchors circadian rhythm. Midday face sun ages you.",
              psl: ["Misc"]),
        .init(id: "diet", title: "Anti-Inflammatory Diet", category: "Diet", difficulty: "Daily",
              summary: "Reduce systemic inflammation that shows in the face.",
              steps: [
                "Cut seed oils, refined sugar, ultra-processed foods",
                "Eat whole foods: meat, fish, eggs, vegetables, fruit, rice",
                "Omega 3: 2g EPA+DHA per day",
                "Identify food sensitivities",
              ],
              notes: "Acne, puffy eyes, dull skin are often dietary.",
              psl: ["Misc", "Angularity"]),
        .init(id: "grooming", title: "Grooming", category: "Style", difficulty: "Weekly",
              summary: "Free wins from haircut, brows, and facial hair shaping.",
              steps: [
                "Get a haircut that fits your face shape",
                "Trim eyebrows, clean unibrow only",
                "Define jawline with stubble or shaved-clean",
                "Whiten teeth -- strips 2 weeks, 1x/year",
              ],
              notes: "Highest-leverage day in facemaxxing is the day you get a great haircut.",
              psl: ["Harmony", "Misc"]),
        .init(id: "lean", title: "Get Lean", category: "Body", difficulty: "Months",
              summary: "Body fat below 15% reveals jawline, cheekbones, orbital bones.",
              steps: [
                "Maintenance calories minus 300 to 500",
                "Protein: 1g per pound of goal bodyweight",
                "Lift weights 3 to 4 days per week",
                "Walk 8000+ steps daily",
              ],
              notes: "Most face fat is body fat. No spot reduction. Get lean and the face follows.",
              psl: ["Angularity", "Dimorphism"]),
        .init(id: "hairmaxxing", title: "Hair Retention", category: "Hair", difficulty: "Daily",
              summary: "Keep the hair you have. Retention beats regrowth by a wide margin.",
              steps: [
                "Photograph your hairline and crown under the same light every 3 months",
                "Topical minoxidil 5% once or twice daily if you see recession",
                "Ketoconazole shampoo 2x/week for scalp inflammation",
                "Talk to a doctor before finasteride, it is a real drug with real side effects",
              ],
              notes: "Hair loss is progressive. Early treatment preserves far more than late treatment.",
              psl: ["Harmony", "Misc"]),
        .init(id: "hairstyle", title: "Hair Styling", category: "Hair", difficulty: "Weekly",
              summary: "Volume and shape at the top of the head lengthen and frame the face.",
              steps: [
                "Blow dry upward and back on cool to medium heat, not flat down",
                "Use a matte clay or paste, not a wet-look gel",
                "Book a trim every 4 to 6 weeks to keep the shape",
                "Match the fade height to your face shape",
              ],
              notes: "Hair is the largest frame around your face and the fastest thing here to change.",
              psl: ["Harmony", "Misc"]),
        .init(id: "undereye", title: "Undereye Care", category: "Skin", difficulty: "Daily",
              summary: "Reduce dark circles and hollowing from fluid, sleep, and allergies.",
              steps: [
                "Sleep with your head slightly elevated to drain overnight fluid",
                "Cold compress for 2 minutes in the morning",
                "Treat allergies, chronic rhinitis causes allergic shiners",
                "Sunscreen and a bland moisturizer, no harsh actives",
              ],
              notes: "Most dark circles are shadow from hollowing or fluid, not pigment.",
              psl: ["Harmony", "Misc"]),
        .init(id: "nasal", title: "Nasal Breathing", category: "Posture", difficulty: "Daily",
              summary: "Mouth breathing drops the jaw, lengthens the midface, and dries the airway.",
              steps: [
                "If you cannot breathe through both nostrils, see an ENT",
                "Nasal strips or dilators at night while you retrain",
                "Saline rinse daily during allergy season",
                "Close the lips and breathe through the nose during light cardio",
              ],
              notes: "Chronic mouth breathing is the mechanism behind poor jaw posture. Mewing sits on top of this.",
              psl: ["Harmony", "Angularity"]),
        .init(id: "teeth", title: "Dental and Bite", category: "Style", difficulty: "Ongoing",
              summary: "Teeth are central to the smile and the bite sets the lower third of the face.",
              steps: [
                "Cleaning every 6 months, floss nightly",
                "Ask an orthodontist about crowding or an overbite",
                "Whitening strips for 2 weeks, once a year at most",
                "Fix a chipped or discoloured front tooth before anything else",
              ],
              notes: "Orthodontics is the only intervention here that moves actual bone and teeth.",
              psl: ["Harmony", "Angularity"]),
        .init(id: "neck", title: "Neck Training", category: "Muscle", difficulty: "10 min, 3x/week",
              summary: "A thicker neck squares the jaw-to-shoulder transition.",
              steps: [
                "Neck harness or plate curls: 3 sets of 15, slow tempo",
                "Neck extensions and lateral flexion, light weight only",
                "Never train the neck through pain or with jerky reps",
                "Two to three sessions per week, never consecutive days",
              ],
              notes: "The neck responds fast and holds the change. Start with bodyweight for the first month.",
              psl: ["Dimorphism", "Angularity"]),
        .init(id: "shoulders", title: "Shoulder Width", category: "Body", difficulty: "3x/week",
              summary: "Wide shoulders make the head and waist read smaller by contrast.",
              steps: [
                "Lateral raises: 4 sets of 15 to 20, light and strict",
                "Overhead press: 3 sets of 5 to 8, heavy",
                "Rear delt flyes to balance the front and fix posture",
                "Train shoulders 2 to 3 times per week",
              ],
              notes: "Shoulder-to-waist ratio is one of the strongest read-at-a-glance signals.",
              psl: ["Dimorphism"]),
        .init(id: "voice", title: "Voice and Speech", category: "Style", difficulty: "10 min/day",
              summary: "Pace, resonance, and volume change how you land more than pitch does.",
              steps: [
                "Breathe from the diaphragm, not the chest",
                "Slow down and use full stops instead of filler words",
                "Record yourself reading a page aloud once a week and listen back",
                "Hydrate, and swallow instead of clearing your throat",
              ],
              notes: "Nobody sees your face without also hearing you. Recording is the entire method.",
              psl: ["Dimorphism", "Misc"]),
        .init(id: "actives", title: "Actives Progression", category: "Skin", difficulty: "Nightly",
              summary: "Add one active at a time once the basic routine has been stable for a month.",
              steps: [
                "Retinoid first: adapalene 0.1% two nights a week, build to nightly over 8 weeks",
                "Azelaic acid 10% for redness and post-acne marks",
                "Niacinamide 5% morning for barrier and oil control",
                "Never start two actives in the same month",
              ],
              notes: "Irritation is not progress. Back off the frequency.",
              psl: ["Harmony", "Misc"]),
        .init(id: "cardio", title: "Cardio Base", category: "Recovery", difficulty: "3x/week",
              summary: "Aerobic fitness improves skin perfusion, sleep depth, and stress load.",
              steps: [
                "Zone 2: 30 to 45 minutes at conversational pace, 3 times per week",
                "One harder interval session per week once the base is built",
                "Walk after meals to blunt glucose spikes",
                "Do not stack hard cardio on heavy lifting days if recovery is thin",
              ],
              notes: "Better circulation and deeper sleep show up in the face within weeks.",
              psl: ["Harmony", "Misc"]),
        .init(id: "stress", title: "Stress and Cortisol", category: "Recovery", difficulty: "Daily",
              summary: "Chronic stress drives puffiness, acne, jaw clenching, and poor sleep.",
              steps: [
                "Fixed wake time, seven days a week",
                "Ten minutes of breathwork or a walk without a phone",
                "Cap caffeine at 400mg and stop by early afternoon",
                "Check for night clenching, ask your dentist about wear on the molars",
              ],
              notes: "If you clench, a night guard comes before any chewing protocol.",
              psl: ["Harmony", "Misc"]),
        .init(id: "photos", title: "Angles and Photos", category: "Style", difficulty: "Once",
              summary: "Learn how you actually photograph instead of guessing from the mirror.",
              steps: [
                "Shoot from eye level or slightly above, never from below",
                "Use a longer lens or step back, close phone selfies distort the nose",
                "Front-on window light, no overhead lighting",
                "Take a front, three-quarter, and profile shot monthly",
              ],
              notes: "The mirror is reversed and the phone lens is wide. A monthly three-angle set is the only honest record.",
              psl: ["Misc"]),
    ]
}
